# cloudbuild.yaml
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/claude-chat-app", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/claude-chat-app"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "claude-chat-app",
        "--image",
        "gcr.io/$PROJECT_ID/claude-chat-app",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "5000",
        "--memory",
        "1Gi",
        "--cpu",
        "1",
        "--max-instances",
        "1",
        "--min-instances",
        "0",
        "--timeout",
        "600s",
        "--concurrency",
        "80",
        "--service-account",
        "claude-chat-app@$PROJECT_ID.iam.gserviceaccount.com",
        "--set-env-vars",
        "GCS_BUCKET_NAME=claude_chat_backups",
        "--set-secrets",
        "ANTHROPIC_API_KEY=anthropic-api-key:latest,SECRET_KEY=flask-secret-key:latest,GITHUB_TOKEN=github-token:latest",
        "--cpu-idle",
        "--session-affinity=false",
      ]

images:
  - "gcr.io/$PROJECT_ID/claude-chat-app"
