steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/claude-chat-app-staging', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/claude-chat-app-staging']

  # Deploy container image to Cloud Run (staging)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'claude-chat-app-staging', 
           '--image', 'gcr.io/$PROJECT_ID/claude-chat-app-staging', 
           '--region', 'us-central1',
           '--platform', 'managed',
           '--allow-unauthenticated',
           '--port', '5000',
           '--memory', '1Gi',
           '--cpu', '1',
           '--max-instances', '1',
           '--service-account', 'claude-chat-app@$PROJECT_ID.iam.gserviceaccount.com',
           '--set-env-vars', 'GCS_BUCKET_NAME=claude_chat_backups_staging',
           '--set-secrets', 'ANTHROPIC_API_KEY=anthropic-api-key:latest,SECRET_KEY=flask-secret-key:latest']

images:
  - 'gcr.io/$PROJECT_ID/claude-chat-app-staging'
