name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to GitHub Container Registry to pull base image
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      # Authenticate to Google Cloud using service account key
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # Set up Google Cloud SDK
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      # Configure Docker to use gcloud as credential helper
      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker

      # Build the container image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/stefanoski-generic-code/claude-chat-app .

      # Push the container image
      - name: Push Docker image
        run: |
          docker push gcr.io/stefanoski-generic-code/claude-chat-app

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy claude-chat-app \
            --image gcr.io/stefanoski-generic-code/claude-chat-app \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --port 5000 \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 1 \
            --min-instances 0 \
            --timeout 600s \
            --concurrency 80 \
            --service-account claude-chat-app@stefanoski-generic-code.iam.gserviceaccount.com \
            --set-env-vars GCS_BUCKET_NAME=claude_chat_backups \
            --set-secrets ANTHROPIC_API_KEY=anthropic-api-key:latest,SECRET_KEY=flask-secret-key:latest,GITHUB_TOKEN=github-token:latest
