name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate to Google Cloud using service account key
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # Set up Google Cloud SDK
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      # Configure Docker for GCP
      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Extract metadata for Docker
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gcr.io/scottstef/claude-chat-app
          tags: |
            type=raw,value=latest
            type=sha,format=short

      # Build and push the application image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy claude-chat-app \
            --image gcr.io/scottstef/claude-chat-app:latest
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --port 5000 \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 1 \
            --min-instances 0 \
            --timeout 600s \
            --concurrency 80 \
            --service-account claude-chat-app@stefanoski-generic-code.iam.gserviceaccount.com \
            --set-env-vars GCS_BUCKET_NAME=claude_chat_backups \
            --set-secrets ANTHROPIC_API_KEY=anthropic-api-key:latest,SECRET_KEY=flask-secret-key:latest,GITHUB_TOKEN=github-token:latest
