name: Deploy Application

on:
  push:
    branches: [main, master] # Trigger on pushes to main or master
  pull_request:
    branches: [main, master] # Optional: build but don't deploy on PRs
  workflow_dispatch: # Allow manual triggering

env:
  APP_IMAGE_NAME: claude-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      # Generate version tag (commit SHA + date)
      - name: Generate version tag
        id: version
        run: |
          SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)
          echo "version=${SHA_SHORT}-$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      # Build and push application image
      - name: Build and push application image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }} # Only push on non-PR events
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.APP_IMAGE_NAME }}:latest
            ghcr.io/${{ github.actor }}/${{ env.APP_IMAGE_NAME }}:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Optional: Run tests on the built image
      - name: Test the image
        run: |
          echo "Running tests on the built image..."
          # Add your test commands here
          # For example: docker run --rm ghcr.io/${{ github.actor }}/${{ env.APP_IMAGE_NAME }}:${{ steps.version.outputs.version }} pytest
