name: Build and Deploy to GCP

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name if different
  workflow_dispatch:    # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/claude-chat-app .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/claude-chat-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy claude-chat-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/claude-chat-app \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --port 5000 \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 1 \
          --min-instances 0 \
          --timeout 600s \
          --concurrency 80 \
          --service-account claude-chat-app@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
          --set-env-vars GCS_BUCKET_NAME=claude_chat_backups \
          --set-secrets "ANTHROPIC_API_KEY=anthropic-api-key:latest,SECRET_KEY=flask-secret-key:latest,GITHUB_TOKEN=github-token:latest"